// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Thread struct {
	ID        string    `json:"id"`
	User      *User     `json:"user"`
	Title     string    `json:"title"`
	PostCount int       `json:"postCount"`
	Category  *Category `json:"category"`
	CreatedAt string    `json:"createdAt"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Access   int    `json:"access"`
	Avatar   string `json:"avatar"`
}

type UserAndToken struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}
